### ISSUE TITLE
Please do a release

### ISSUE THREAD

**Issue by bastien-roucaries** [es-shims/String.prototype.trimRight#61]
This is needed for node (>10) in debian

**Comment by ljharb** [comment]
I'm not sure what you mean. What part of the unreleased changes is needed for node in debian?

**Comment by ljharb** [comment]
Either way, I released v2.1.0, but I can't for the life of me think why it would matter - v2.0.0 and v2.1.0 both support down to node like 0.6, and nothing in the release should be applicable to debian.
